#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@ if/end data.values.target.contour:

#@overlay/match by=overlay.subset({"kind":"ClusterRole"}), expects=1
---
rules:
#@overlay/append
- apiGroups: ["projectcontour.io"]
  resources: ["httpproxies"]
  verbs: ["get", "watch", "list"]