#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata": {"name": "external-dns"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by=overlay.map_key("name")
      - name: external-dns
        #@overlay/replace
        image: #@ data.values.image.name
        #@overlay/match missing_ok=True
        imagePullPolicy: #@ data.values.image.pullPolicy