#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"Ingress", "metadata": {"name": "testapp"}})
---
spec:
  rules:
  #@overlay/match by=overlay.index(0)
  - host: #@ "testapp.{}".format(data.values.wildcard_domain)
  #@overlay/match missing_ok=True
  tls:
  - hosts:
    - #@ "testapp.{}".format(data.values.wildcard_domain)
    secretName: wildcard