---
apiVersion: v1
kind: Secret
metadata:
  name: certs-config
  namespace: dev-platform-ctrl
  annotations:
    kapp.k14s.io/change-group: "certs.tkgdev.failk8s.com/package"
    kapp.k14s.io/change-rule.insert: "upsert after upserting certs.tkgdev.failk8s.com/rbac"
stringData:
  values.yml: 