---
apiVersion: packaging.carvel.dev/v1alpha1
kind: InstalledPackage
metadata:
  name: knative-serving
  namespace: dev-platform-ctrl
spec:
  serviceAccountName: dev-platform-ctrl-sa
  packageVersionRef:
    packageName: knative-serving.tkgdev.failk8s.com
    versionSelection:
      constraints: "0.21.0"
      prereleases: {}
  values:
  - secretRef:
      name: knative-serving-config