apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-serving-ctrl-sa
  namespace: dev-platform-ctrl
  annotations:
    kapp.k14s.io/change-group: "knative-serving.tkgdev.failk8s.com/rbac"
    kapp.k14s.io/change-rule.delete: "delete after deleting knative-serving.tkgdev.failk8s.com/package"