---
apiVersion: packaging.carvel.dev/v1alpha1
kind: InstalledPackage
metadata:
  name: dns
  namespace: dev-platform-ctrl
spec:
  serviceAccountName: dev-platform-ctrl-sa
  packageVersionRef:
    packageName: dns.tkgdev.failk8s.com
    versionSelection:
      constraints: "1.0.0"
      prereleases: {}
  values:
  - secretRef:
      name: dns-config