{
    "domain": "tkgdev.failk8s.com",
    "repository": {
        "name": "tkgdev-repo",
        "version": "1.0.0"
    },
    "registry": "quay.io/failk8s",
    "paths": {
        "sources": {
            "packages": "src/packages",
            "repository": "src/repo",
            "templates": "src/templates"
        },
        "target": {
            "packages": "target/packages",
            "repository": "target/repo",
            "k8s": "target/k8s"
        }
    },
    "packages": [
        {
            "name": "cert-manager",
            "displayName": "Cert Manager",
            "versions": [
                "1.1.0",
                "1.3.1",
                "1.4.0"
            ]
        },
        {
            "name": "contour",
            "displayName": "Contour",
            "versions": [
                "1.10.0",
                "1.15.0"
            ]
        },
        {
            "name": "certs",
            "displayName": "Certificates for Development",
            "versions": [
                "1.0.0"
            ]
        },
        {
            "name": "secretcopier-operator",
            "displayName": "Secret Copier Operator for Development",
            "versions": [
                "1.0.0"
            ]
        },
        {
            "name": "dns",
            "displayName": "DNS registration",
            "versions": [
                "1.0.0"
            ]
        },
        {
            "name": "registry",
            "displayName": "OCI Registry",
            "versions": [
                "1.0.0"
            ]
        },
        {
            "name": "knative-serving",
            "displayName": "KNative Serving",
            "versions": [
                "0.22.0"
            ]
        },
        {
            "name": "testapp",
            "displayName": "K8S test application",
            "versions": [
                "1.0.0"
            ]
        },
        {
            "name": "testknativeapp",
            "displayName": "Knative test application",
            "versions": [
                "1.0.0"
            ]
        },
        {
            "name": "dev-platform",
            "displayName": "Development platform",
            "versions": [
                "1.0.0",
                "1.0.1"
            ]
        }
    ]
}