---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: dns
  namespace: dev-platform-ctrl
  annotations:
    kapp.k14s.io/change-group: "dns.tkgdev.failk8s.com/package"
    kapp.k14s.io/change-rule.insert: "upsert after upserting dns.tkgdev.failk8s.com/rbac"
spec:
  serviceAccountName: dns-ctrl-sa
  packageRef:
    refName: dns.tkgdev.failk8s.com
    versionSelection:
      constraints: "1.0.0"
      prereleases: {}
  values:
  - secretRef:
      name: dns-config