---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-platform-ctrl
  annotations:
    kapp.k14s.io/change-group: "tkgdev.failk8s.com/namespace"
    kapp.k14s.io/change-rule.delete: "delete after deleting tkgdev.failk8s.com/rbac"