---
apiVersion: v1
kind: Namespace
metadata:
  name: dev-platform
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-platform-sa
  namespace: dev-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dev-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: dev-platform-sa
    namespace: dev-platform
