#@ load("@ytt:data", "data")

#@ for package in data.values.packages:
---
apiVersion: package.carvel.dev/v1alpha1
kind: Package
metadata:
  name: #@ "{}.{}".format(package.name, data.values.domain, package.version)
spec:
  publicName: #@ "{}.{}".format(package.name, data.values.domain, data.values.domain)
  version: #@ package.version
  template:
    spec:
      syncPeriod: 30s
      fetch:
        - imgpkgBundle:
            image: #@ "{}/{}-package:{}".format(data.values.registry, package.name, package.version)
      template:
        - ytt:
            ignoreUnknownComments: true
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp:
            rawOptions: ["--wait-timeout=5m"]
#@ end 