---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: contour
  namespace: dev-platform-ctrl
  annotations:
    kapp.k14s.io/change-group: "contour.tkgdev.failk8s.com/package"
    kapp.k14s.io/change-rule.insert: "upsert after upserting contour.tkgdev.failk8s.com/rbac"
spec:
  serviceAccountName: contour-ctrl-sa
  packageRef:
    refName: contour.tkgdev.failk8s.com
    versionSelection:
      constraints: "1.15.0"
      prereleases: {}
  values:
  - secretRef:
      name: contour-config