---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: certs
  namespace: dev-platform-ctrl
spec:
  serviceAccountName: dev-platform-ctrl-sa
  packageRef:
    refName: certs.tkgdev.failk8s.com
    versionSelection:
      constraints: "1.0.0"
      prereleases: {}
  values:
  - secretRef:
      name: certs-config