apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cert-manager.tkgdev.failk8s.com.1.4.0
  namespace: kapp-controller-packaging-global
spec:
  refName: cert-manager.tkgdev.failk8s.com
  version: 1.4.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/cert-manager-package:1.4.0
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
