apiVersion: v1
kind: ServiceAccount
metadata:
  name: testapp-ctrl-sa
  namespace: dev-platform-ctrl
  annotations:
    kapp.k14s.io/change-group.1: "testapp.tkgdev.failk8s.com/rbac"
    kapp.k14s.io/change-group.2: "tkgdev.failk8s.com/rbac"
    kapp.k14s.io/change-rule.insert: "upsert after upserting tkgdev.failk8s.com/namespace"
    kapp.k14s.io/change-rule.delete: "delete after deleting testapp.tkgdev.failk8s.com/package"