---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: secretcopier-operator
  namespace: dev-platform-ctrl
  annotations:
    kapp.k14s.io/change-group: "secretcopier-operator.tkgdev.failk8s.com/package"
    kapp.k14s.io/change-rule.insert: "upsert after upserting secretcopier-operator.tkgdev.failk8s.com/rbac"
spec:
  serviceAccountName: secretcopier-operator-ctrl-sa
  packageRef:
    refName: secretcopier-operator.tkgdev.failk8s.com
    versionSelection:
      constraints: "1.0.0"
      prereleases: {}
  values:
  - secretRef:
      name: secretcopier-operator-config