apiVersion: v1
kind: ServiceAccount
metadata:
  name: secretcopier-operator-ctrl-sa
  namespace: dev-platform-ctrl
  annotations:
    kapp.k14s.io/change-group: "secretcopier-operator.tkgdev.failk8s.com/rbac"
    kapp.k14s.io/change-rule.delete: "delete after deleting secretcopier-operator.tkgdev.failk8s.com/package"