apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageVersion
metadata:
  name: knative-serving.tkgdev.failk8s.com.0.21.0
spec:
  packageName: knative-serving.tkgdev.failk8s.com
  version: 0.21.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: quay.io/failk8s/knative-serving-package:0.21.0
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
