---
apiVersion: imgpkg.carvel.dev/v1alpha1
images:
- annotations:
    kbld.carvel.dev/id: quay.io/failk8s/cert-manager-package:1.1.0
  image: quay.io/failk8s/cert-manager-package@sha256:04bd4e6198a84944cbb763cd5064ba18470053abda4098345c1747850f14b6d6
- annotations:
    kbld.carvel.dev/id: quay.io/failk8s/cert-manager-package:1.3.1
  image: quay.io/failk8s/cert-manager-package@sha256:2a26fe8c608f8f01ea65ee1a3fd3bd75d005ac723af37249158a62b0927a2676
- annotations:
    kbld.carvel.dev/id: quay.io/failk8s/contour-package:1.10.0
  image: quay.io/failk8s/contour-package@sha256:b6fc886398cfd42ca8e9423951a336929ec4282e6c2cacbc913ca432ba5c9d9a
- annotations:
    kbld.carvel.dev/id: quay.io/failk8s/knative-serving-package:0.21.0
  image: quay.io/failk8s/knative-serving-package@sha256:cbc3b4d8c49caaca7303c7361d71707672fa7462fe1727b997c9ca3e45283e11
kind: ImagesLock
