apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-ctrl-sa
  namespace: dev-platform-ctrl
  annotations:
    kapp.k14s.io/change-group: "registry.tkgdev.failk8s.com/rbac"
    kapp.k14s.io/change-rule.delete: "delete after deleting registry.tkgdev.failk8s.com/package"