---
apiVersion: packaging.carvel.dev/v1alpha1
kind: InstalledPackage
metadata:
  name: cert-manager
  namespace: dev-platform-ctrl
spec:
  serviceAccountName: dev-platform-ctrl-sa
  packageVersionRef:
    packageName: cert-manager.tkgdev.failk8s.com
    versionSelection:
      constraints: "1.3.1"
      prereleases: {}
  values:
  - secretRef:
      name: cert-manager-config