---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    email: REPLACE_ME
    privateKeySecretRef:
      name: wildcard-acme
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        route53:
          region: REPLACE_ME
          accessKeyID: REPLACE_ME
          secretAccessKeySecretRef:
            name: aws-route53-creds
            key: aws-credentials
    - http01:
        ingress:
          class: REPLACE_ME
