---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
  namespace: REPLACE_ME
spec:
  secretName: wildcard
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
  - REPLACE_ME
