#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:base64", "base64")

#@overlay/match by=overlay.subset({"kind":"Secret", "metadata": {"name": "aws-route53-creds"}})
---
data:
  aws-credentials: #@ base64.encode(data.values.aws.secret_access_key)


#@overlay/match by=overlay.subset({"kind":"ClusterIssuer", "metadata": {"name": "lets-encrypt"}})
---
spec:
  acme:
    email: #@ data.values.aws.certs.email
    solvers:
    #@overlay/match by=lambda i,l,r: "dns01" in l
    - dns01:
        route53:
          region: #@ data.values.aws.certs.region
          accessKeyID: #@ data.values.aws.access_key_id
    #@overlay/match by=lambda i,l,r: "http01" in l
    - http01:
        ingress:
          class: #@ data.values.ingress.ingress_class