#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def config():
namespace: #@ data.values.testapp.namespace 
privileged_clusterrole_name: #@ data.values.privileged_clusterrole_name
wildcard_domain: #@ data.values.wildcard_domain
#@ end

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata":{"name":"testapp-config"}})
---
stringData:
  values.yml: #@ yaml.encode(config())
