#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def config():
namespace: #@ data.values.ingress.namespace
domain: #@ data.values.domain
wildcard_domain: #@ data.values.wildcard_domain
privileged_clusterrole_name: #@ data.values.privileged_clusterrole_name
#@ end

#@overlay/match by=overlay.subset({"kind": "Secret", "metadata":{"name":"contour-config"}})
---
stringData:
  values.yml: #@ yaml.encode(config())
