#@ load("@ytt:data", "data")
#@ load("@ytt:assert", "assert")

#@ if data.values.domain:
#@   data.values.domain!="REPLACE_ME" or assert.fail("data.values.domain can not be empty or REPLACE_ME")
#@ else:
#@   assert.fail("data.values.domain can not be empty or REPLACE_ME")
#@ end

#@ if data.values.wildcard_domain:
#@   data.values.wildcard_domain!="REPLACE_ME" or assert.fail("data.values.wildcard_domain can not be empty or REPLACE_ME")
#@ else:
#@   assert.fail("data.values.wildcard_domain can not be empty or REPLACE_ME")
#@ end
