#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"SecretCopierConfig","metadata": {"name": "wildcard"}})
---
spec:
  rules:
  #@overlay/match by=lambda i,l,r: "sourceSecret" in l
  - sourceSecret:
      namespace: #@ data.values.ingress.namespace
