apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: cert-manager
  namespace: tanzu-extensions
spec:
  syncPeriod: 5m
  serviceAccountName: cert-manager-extension-sa
  fetch:
    - imgpkgBundle:
        image: projects.registry.vmware.com/tce/cert-manager-extension-templates:dev
  template:
    - ytt:
        ignoreUnknownComments: true
        paths:
          - config/
    - kbld: {}
  deploy:
    - kapp:
        rawOptions: ["--wait-timeout=5m"]
